name: Solar Edge CI
on: [push]
jobs:
  pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
      - name: Source Checkout
        uses: actions/checkout@v1
      - name: Bundle Install
        run: |
          gem install bundler -v 2.1.4
          bundle install --jobs 4 --retry 3
      - name: Rubocop Linting
        run: |
          bundle exec rake rubocop
      - name: Buildx Image Build and Push
        run: |
          bundle exec rake docker_buildx
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
